package bookstore.pbean;
// Generated 2006/07/22 0:31:30 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * TBook generated by hbm2java
 */

public class TBook  implements java.io.Serializable {


    // Fields    

     private int id;
     private String isbn;
     private String title;
     private String author;
     private String publisher;
     private int price;
     private Set TOrderDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public TBook() {
    }

	/** minimal constructor */
    public TBook(int id, String isbn, String title, String author, String publisher, int price) {
        this.id = id;
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publisher = publisher;
        this.price = price;
    }
    
    /** full constructor */
    public TBook(int id, String isbn, String title, String author, String publisher, int price, Set TOrderDetails) {
        this.id = id;
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publisher = publisher;
        this.price = price;
        this.TOrderDetails = TOrderDetails;
    }
    

   
    // Property accessors

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    public Set getTOrderDetails() {
        return this.TOrderDetails;
    }
    
    public void setTOrderDetails(Set TOrderDetails) {
        this.TOrderDetails = TOrderDetails;
    }
   








}
