package bookstore.pbean;
// Generated 2006/07/22 0:31:30 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * TCustomer generated by hbm2java
 */

public class TCustomer  implements java.io.Serializable {


    // Fields    

     private int id;
     private String uid;
     private String passwordmd5;
     private String name;
     private String email;
     private Set TOrders = new HashSet(0);


    // Constructors

    /** default constructor */
    public TCustomer() {
    }

	/** minimal constructor */
    public TCustomer(int id, String uid, String passwordmd5, String name, String email) {
        this.id = id;
        this.uid = uid;
        this.passwordmd5 = passwordmd5;
        this.name = name;
        this.email = email;
    }
    
    /** full constructor */
    public TCustomer(int id, String uid, String passwordmd5, String name, String email, Set TOrders) {
        this.id = id;
        this.uid = uid;
        this.passwordmd5 = passwordmd5;
        this.name = name;
        this.email = email;
        this.TOrders = TOrders;
    }
    

   
    // Property accessors

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getPasswordmd5() {
        return this.passwordmd5;
    }
    
    public void setPasswordmd5(String passwordmd5) {
        this.passwordmd5 = passwordmd5;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Set getTOrders() {
        return this.TOrders;
    }
    
    public void setTOrders(Set TOrders) {
        this.TOrders = TOrders;
    }
   








}
